In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python yang digunakan untuk komputasi matriks. Matplotlib merupakan library python untuk presentasi data berupa grafik atau plot.....

In [23]:
dataset = pd.read_csv('Data-Tugas3_DM.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [24]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Japan' 48.0 nan]
 ['India' nan 78000.0]
 ['UAE' 50.0 28000.0]
 ['Australia' nan 56000.0]
 ['Korea' 39.0 44000.0]]


In [25]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes'
 'Yes' 'No']


In [26]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [27]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 60000.0]
 ['France' 35.0 58000.0]
 ['Spain' 40.5 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Japan' 48.0 60000.0]
 ['India' 40.5 78000.0]
 ['UAE' 50.0 28000.0]
 ['Australia' 40.5 56000.0]
 ['Korea' 39.0 44000.0]]


In [28]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [29]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 40.0 60000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.5 52000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 48.0 60000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 40.5 78000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 50.0 28000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 40.5 56000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 39.0 44000.0]]


In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [31]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 1 1 1 0]


In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [33]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 48.0 60000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 40.0 60000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 27.0 48000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 40.5 56000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 39.0 44000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 50.0 28000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 40.5 78000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 58000.0]]


In [34]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.5 52000.0]]


In [35]:
print(y_train)

[0 0 1 1 1 0 0 1 0 1 1 1]


In [36]:
print(y_test)

[0 1 0]


In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [38]:
print(x_train)

[[0.0 0.0 1.0 -0.30151134457776363 -0.3015113445777637
  -0.30151134457776363 -0.30151134457776363 -0.30151134457776363
  -1.4448855601907118 -0.3454442679267334]
 [0.0 0.0 0.0 -0.30151134457776363 3.3166247903554007
  -0.30151134457776363 -0.30151134457776363 -0.30151134457776363
  1.13441428279436 0.06908885358534668]
 [0.0 0.0 1.0 -0.30151134457776363 -0.3015113445777637
  -0.30151134457776363 -0.30151134457776363 -0.30151134457776363
  -0.01194120297678308 0.06908885358534668]
 [0.0 0.0 0.0 -0.30151134457776363 -0.3015113445777637
  -0.30151134457776363 3.3166247903554 -0.30151134457776363
  -1.8747688673548906 -0.7599773894388134]
 [1.0 0.0 0.0 -0.30151134457776363 -0.3015113445777637
  -0.30151134457776363 -0.30151134457776363 -0.30151134457776363
  0.05970601488391336 -0.20726656075604002]
 [0.0 1.0 0.0 -0.30151134457776363 -0.3015113445777637
  -0.30151134457776363 -0.30151134457776363 -0.30151134457776363
  0.5612365399087884 0.8981550966095069]
 [0.0 0.0 0.0 -0.30151134457776

In [39]:
print(x_test)

[[0.0 0.0 0.0 -0.30151134457776363 -0.3015113445777637
  -0.30151134457776363 3.3166247903554 -0.30151134457776363
  -0.29853007441956886 0.13817770717069336]
 [0.0 1.0 0.0 -0.30151134457776363 -0.3015113445777637
  -0.30151134457776363 -0.30151134457776363 -0.30151134457776363
  1.13441428279436 1.3817770717069335]
 [0.0 0.0 0.0 -0.30151134457776363 -0.3015113445777637
  -0.30151134457776363 3.3166247903554 -0.30151134457776363
  0.05970601488391336 -0.48362197509742677]]
